name: CI SauceDemo Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Set ALLURE_ENV
      run: echo "ALLURE_ENV=CI" >> $GITHUB_ENV

    - name: Download previous Allure history
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: history

    - name: Run UI Tests
      run: dotnet test SauceDemoAutomationUI/SauceDemoAutomationUI.csproj --logger:"console;verbosity=detailed"

    - name: Run API Tests
      run: dotnet test SauceDemoAutomationAPI/SauceDemoAutomationAPI.csproj --logger:"console;verbosity=detailed"

    - name: Copy Allure Results to unified folder
      run: |
        mkdir -p TestResults/$ALLURE_ENV
        cp -r SauceDemoAutomationUI/bin/Debug/net8.0/allure-results/* TestResults/$ALLURE_ENV || true
        cp -r SauceDemoAutomationAPI/bin/Debug/net8.0/allure-results/* TestResults/$ALLURE_ENV || true

    - name: Copy history into results
      run: |
        mkdir -p TestResults/$ALLURE_ENV/history
        cp -r history/* TestResults/$ALLURE_ENV/history/ || true

    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate TestResults/$ALLURE_ENV --clean -o AllureReport

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: AllureReport

    - name: Upload Allure history
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: AllureReport/history
