name: CI SauceDemo Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Install browsers and drivers
      run: |
        sudo apt-get update

        # Chrome + ChromeDriver
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver

        # Firefox + GeckoDriver
        sudo apt-get install -y firefox-geckodriver

        # Edge + EdgeDriver
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-edge.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable unzip

        EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        DRIVER_URL="https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip"
        wget -q $DRIVER_URL -O msedgedriver.zip
        unzip msedgedriver.zip
        sudo mv msedgedriver /usr/local/bin/
        rm msedgedriver.zip

        echo "=== Installed versions ==="
        google-chrome --version || google-chrome-stable --version
        chromedriver --version
        firefox --version
        geckodriver --version
        microsoft-edge --version || microsoft-edge-stable --version
        msedgedriver --version

    - name: Build project
      run: dotnet build --no-restore

    - name: Run UI Tests
      continue-on-error: true
      run: dotnet test SauceDemoAutomationUI/SauceDemoAutomationUI.csproj --logger:"console;verbosity=detailed"

    - name: Run API Tests
      continue-on-error: true
      run: dotnet test SauceDemoAutomationAPI/SauceDemoAutomationAPI.csproj --logger:"console;verbosity=detailed"

    - name: Copy Allure Results to unified folder
      run: |
        mkdir -p TestResults/AllureResults
        cp -r SauceDemoAutomationUI/bin/Debug/net8.0/allure-results/* TestResults/AllureResults || true
        cp -r SauceDemoAutomationAPI/bin/Debug/net8.0/allure-results/* TestResults/AllureResults || true

    - name: Clone gh-pages branch to get previous Allure history
      run: |
        git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        mkdir -p TestResults/AllureResults/history
        if [ -d "gh-pages/allure/history" ]; then
          cp -r gh-pages/allure/history/* TestResults/AllureResults/history/ || true
        else
          echo "No previous history found"
        fi

    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate TestResults/AllureResults --clean -o AllureReport

    - name: Upload Allure Report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: AllureReport

    - name: Upload Allure history as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: AllureReport/history

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./AllureReport
        destination_dir: allure

