name: CI SauceDemo Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Install Browsers
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable firefox microsoft-edge-stable

    - name: Build project
      run: dotnet build --no-restore

    - name: Run UI Tests
      continue-on-error: true
      run: dotnet test SauceDemoAutomationUI/SauceDemoAutomationUI.csproj --logger:"console;verbosity=detailed"

    - name: Run API Tests
      continue-on-error: true
      run: dotnet test SauceDemoAutomationAPI/SauceDemoAutomationAPI.csproj --logger:"console;verbosity=detailed"

    - name: Copy Allure Results to unified folder
      run: |
        mkdir -p TestResults/AllureResults
        cp -r SauceDemoAutomationUI/bin/Debug/net8.0/allure-results/* TestResults/AllureResults || true
        cp -r SauceDemoAutomationAPI/bin/Debug/net8.0/allure-results/* TestResults/AllureResults || true

    - name: Download previous Allure history
      id: download_history
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: history

    - name: Copy history into results
      if: steps.download_history.outcome == 'success'
      run: |
        echo "Previous history found. Copying..."
        mkdir -p TestResults/AllureResults/history
        cp -r history/* TestResults/AllureResults/history/ || true

    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate TestResults/AllureResults --clean -o AllureReport

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: AllureReport

    - name: Upload Allure history
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: AllureReport/history

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./AllureReport
        destination_dir: allure
